---
- hosts: servers
  become: true

  tasks:
    - name: git clone corda example
      git:
        repo: "https://github.com/corda/samples-java.git"
        dest:  "samples-java"
    
    - name: deploy the cordapp
      command: chdir=samples-java/Basic/cordapp-example ./gradlew deployNodes

